#=========================================================================
# ASIC Design Kit -- FreePDK45 + NanGate Open Cell Library
#=========================================================================
# Author : Christopher Torng
# Date   : June 7, 2019
#

name: skywater-130nm-adk

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - adk

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # Set up the outputs
  - mkdir -p outputs && cd outputs
  - ln -sf ../{adk_view} adk

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  adk: skywater-130nm-adk
  adk_view: view-standard

#-------------------------------------------------------------------------
# Special mflowgen tags
#-------------------------------------------------------------------------

sandbox: False
